
runs-on:ununtu-latest
needs:test #depends on the test job
steps:
  -name:Download test report
  uses:actions/download-artifact@v4
  with:
   name:test-report
   path:download-reports
  -name:Display contents
  run:cat downloaded-reports/test-result.txt
